# Generated by Django 2.1.7 on 2019-03-23 05:34

import app_linkup.utilitarios.genericos
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', app_linkup.utilitarios.genericos.CleanCharField(max_length=100)),
                ('descripcion', app_linkup.utilitarios.genericos.CleanCharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', app_linkup.utilitarios.genericos.CleanCharField(max_length=200)),
                ('apellido', app_linkup.utilitarios.genericos.CleanCharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField(null=True)),
                ('numero_de_documento', app_linkup.utilitarios.genericos.CleanCharField(max_length=25, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('cuenta_de_usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_o_porque', app_linkup.utilitarios.genericos.CleanCharField(max_length=250)),
                ('categoria', models.ForeignKey(on_delete=False, to='app_linkup.Categoria')),
                ('cliente', models.ForeignKey(on_delete=False, to='app_linkup.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', app_linkup.utilitarios.genericos.CleanCharField(max_length=25, unique=True)),
                ('nombre_largo', app_linkup.utilitarios.genericos.CleanCharField(max_length=100)),
                ('tipo_patron', models.IntegerField(choices=[(0, 'Numerico'), (1, 'Alfanumerico')])),
                ('tipo_contribuyente', models.IntegerField(choices=[(0, 'Documento para nacionales solamente'), (1, 'Documento para extranjeros solamente'), (2, 'Documento para nacionales y extranjeros')])),
                ('tipo_longitud', models.IntegerField(choices=[(0, 'Exacta'), (1, 'Inexacta')])),
                ('longitud', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=False, to='app_linkup.TipoDocumento'),
        ),
    ]
