# Generated by Django 2.1.7 on 2019-03-23 22:06

import app_linkup.models.categoria
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_linkup', '0002_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=app_linkup.models.categoria.Categoria.image_path),
        ),
    ]
