# Generated by Django 2.1.7 on 2019-03-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_linkup', '0003_auto_20190323_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
