# Generated by Django 2.1.7 on 2019-03-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_linkup', '0004_auto_20190323_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
